//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryManagementSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор успешно добавлен.
        /// </summary>
        internal static string AuthorAdded {
            get {
                return ResourceManager.GetString("AuthorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор уже существует!.
        /// </summary>
        internal static string AuthorAlreadyExists {
            get {
                return ResourceManager.GetString("AuthorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения не может быть в будущем..
        /// </summary>
        internal static string AuthorDateOfBirthInvalid {
            get {
                return ResourceManager.GetString("AuthorDateOfBirthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения автора не указана..
        /// </summary>
        internal static string AuthorDateOfBirthIsEmpty {
            get {
                return ResourceManager.GetString("AuthorDateOfBirthIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор удален.
        /// </summary>
        internal static string AuthorDeleted {
            get {
                return ResourceManager.GetString("AuthorDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор для этой книги не найден!.
        /// </summary>
        internal static string AuthorForBookNotFound {
            get {
                return ResourceManager.GetString("AuthorForBookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор автора не может быть пустым..
        /// </summary>
        internal static string AuthorIdIsEmpty {
            get {
                return ResourceManager.GetString("AuthorIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя автора не может быть пустым..
        /// </summary>
        internal static string AuthorNameIsEmpty {
            get {
                return ResourceManager.GetString("AuthorNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя автора не должно превышать 100 символов..
        /// </summary>
        internal static string AuthorNameTooLong {
            get {
                return ResourceManager.GetString("AuthorNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор не найден!.
        /// </summary>
        internal static string AuthorNotFound {
            get {
                return ResourceManager.GetString("AuthorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор обновлен.
        /// </summary>
        internal static string AuthorUpdated {
            get {
                return ResourceManager.GetString("AuthorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга добавлена.
        /// </summary>
        internal static string BookAdded {
            get {
                return ResourceManager.GetString("BookAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга уже существует!.
        /// </summary>
        internal static string BookAlreadyExists {
            get {
                return ResourceManager.GetString("BookAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан автор книги..
        /// </summary>
        internal static string BookAuthorIsEmpty {
            get {
                return ResourceManager.GetString("BookAuthorIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга удалена.
        /// </summary>
        internal static string BookDeleted {
            get {
                return ResourceManager.GetString("BookDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор книги не может быть пустым..
        /// </summary>
        internal static string BookIdIsEmpty {
            get {
                return ResourceManager.GetString("BookIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга не найдена!.
        /// </summary>
        internal static string BookNotFound {
            get {
                return ResourceManager.GetString("BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год издания книги не может быть больше текущего..
        /// </summary>
        internal static string BookPublisherYearInvalid {
            get {
                return ResourceManager.GetString("BookPublisherYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год издания книги не может быть пустым..
        /// </summary>
        internal static string BookPublisherYearIsEmpty {
            get {
                return ResourceManager.GetString("BookPublisherYearIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название книги не может быть пустым..
        /// </summary>
        internal static string BookTitleIsEmpty {
            get {
                return ResourceManager.GetString("BookTitleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название книги не должно превышать 500 символов..
        /// </summary>
        internal static string BookTitleTooLong {
            get {
                return ResourceManager.GetString("BookTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга обновлена.
        /// </summary>
        internal static string BookUpdated {
            get {
                return ResourceManager.GetString("BookUpdated", resourceCulture);
            }
        }
    }
}
